# railway.toml

[build]
  builder = "NIXPACKS"
  build_command = "npm install --legacy-peer-deps && npm run build"

[deploy]
  runtime = "V2"
  numReplicas = 1
  sleepApplication = false

  [deploy.multiRegionConfig]
    us-west1 = { numReplicas = 1 }

  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10
